# Generated by Django 5.0.7 on 2024-07-11 10:24

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
